### ISSUE TITLE
Kafka Registry API Authentication (API_Key, API_Secret)

### ISSUE THREAD

**Issue by oh-john-garcia** [fluent-plugins-nursery/fluent-plugin-parser-avro#2]
It's not clear how can we authenticate (using `API_KEY` and `API_SECRET`) to the Schema Registry endpoint. Are these parameters within the plugin?  @cosmo0920 

**Reference**: https://docs.confluent.io/platform/current/schema-registry/develop/using.html#common-sr-api-usage-examples

**Comment by kenhys** [comment]
@oh-john-garcia 
It seems that the current version of fluent-plugin-parser-avro does not support such a feature yet.
It is better to support authentication.
I'll  dig into it.

**Comment by cosmo0920** [comment]
I've merged https://github.com/fluent-plugins-nursery/fluent-plugin-parser-avro/pull/3 into master and released as v0.3.0.
