### ISSUE TITLE
API Authentication Fix. Enable use_ssl

### ISSUE THREAD

**Issue by oh-john-garcia** [fluent-plugins-nursery/fluent-plugin-parser-avro#6]
I was testing **Basic Auth** but still not able to connect to the Schema Registry API. Traceback attached: [tracebak_fluentd_schema.log](https://github.com/fluent-plugins-nursery/fluent-plugin-parser-avro/files/5948129/tracebak_fluentd_schema.log). 
After some digging, I think the cause might be related to the following line in **`confluent_avro_schema_registry.rb`**:

`Net::HTTP.start(uri.host, uri.port) do |http|`

which should enable **use_ssl**, like the following:

`Net::HTTP.start(uri.host, uri.port, :use_ssl => true) do |http|`

A quick test was successful on our configuration. 
Let us know if that makes sense. Thanks.  @cosmo0920 @kenhys

**Comment by kenhys** [comment]
@oh-john-garcia Thank you for the feedback, it is a reasonable fix.

**Comment by kenhys** [comment]
I've created PR  to fix this issue https://github.com/fluent-plugins-nursery/fluent-plugin-parser-avro/pull/7

**Comment by cosmo0920** [comment]
I'd released the patch as v0.3.1. Closing.

**Comment by oh-john-garcia** [comment]
Thanks for your quick response! I'll check and let you know.
